### PR TITLE
fix: replace deadlocking futures::executor::block_on with runtime-aware dash-async crate (#3432)

### LINKED ISSUE #3432: Deadlock: futures::executor::block_on inside tokio runtime in TrustedHttpContextProvider
## Description

`TrustedHttpContextProvider::get_quorum_public_key()` in `rs-sdk-trusted-context-provider/src/provider.rs` (line ~626) calls `futures::executor::block_on()` when a quorum key is not found in cache and `refetch_if_not_found` is true. This call happens from within a tokio runtime context (the SDK's FFI layer enters the runtime via `wrapper.runtime.block_on(async { ... })`), which causes a **deadlock**.

## Root Cause

The `ContextProvider` trait has a synchronous interface (`fn get_quorum_public_key(...) -> Result<...>`). When the quorum cache misses, the code falls back to:

```rust
futures::executor::block_on(self.find_quorum(...))
```

`find_quorum` makes HTTP requests via `reqwest`. Nesting `futures::executor::block_on` inside a tokio runtime context deadlocks on single-threaded runtimes or panics on multi-threaded runtimes.

## Trigger Conditions

1. SDK created via `dash_sdk_create_trusted` — quorum prefetch is async and the SDK handle is returned immediately (race condition)
2. App issues a query requiring proof verification before the prefetch completes
3. `get_quorum_public_key` is called, cache is empty
4. `futures::executor::block_on` called inside tokio → **deadlock**

Also triggered if a proof references a quorum hash not in the pre-fetched set.

## Impact

- App hangs permanently (denial of service)
- Intermittent — depends on timing of prefetch vs first query
- Affects iOS SDK and any other FFI consumer using the trusted context provider

## Suggested Fixes

1. Use `tokio::task::block_in_place` + `Handle::current().block_on()` for the synchronous fallback
2. Or restructure `ContextProvider` trait to support async operations
3. Or block SDK creation until prefetch completes (ensure SDK is ready before returning handle)
4. Or set `refetch_if_not_found = false` when operating within a tokio context and rely solely on the prefetched cache

## Related

- `dash_sdk_create_trusted` returns SDK before prefetch completes (`rs-sdk-ffi/src/sdk.rs:504-537`)
- The diagnostic HTTP requests to google.com at lines 511-521 should also be removed

## Found By

Security audit of v3.1-dev branch.

### PR DESCRIPTION
**Pull request by lklimek**
## Issue being fixed or feature implemented

Fixes #3432 — `futures::executor::block_on` inside a tokio runtime in `TrustedHttpContextProvider` causes a **deadlock** when quorum cache misses trigger async HTTP fetches.

### Root cause (from #3432)
`ContextProvider::get_quorum_public_key()` is synchronous, but on cache miss it calls `futures::executor::block_on(self.find_quorum(...))` which makes HTTP requests via `reqwest`. Nesting `futures::executor::block_on` inside a tokio runtime deadlocks on single-threaded runtimes or panics on multi-threaded runtimes. This affects the iOS SDK and any FFI consumer using the trusted context provider.

### New crate: `packages/rs-dash-async` (`dash-async`)
Extracted a runtime-aware `block_on` function that correctly handles all three scenarios:
- **No active runtime** → creates a temporary current-thread runtime
- **Current-thread runtime** → spawns a dedicated OS thread with its own runtime (avoids `block_in_place` panic)
- **Multi-thread runtime** → uses `block_in_place` + spawn for efficient bridging

Also includes:
- `AsyncError` error type
- WASM stub that returns graceful `Err` with JSPI reference instead of `unimplemented!()`
- Regression test for the current-thread runtime deadlock scenario (#3432)

### `rs-sdk-trusted-context-provider` — the fix
- **Replaced `futures::executor::block_on`** with `dash_async::block_on` — this is the direct fix for #3432
- Made `TrustedHttpContextProvider` `Clone` (`fallback_provider` changed from `Box<dyn ContextProvider>` to `Arc<dyn ContextProvider>` — only accessed via `&self`, `ContextProvider: Send + Sync`)
- Removed the `#[cfg(target_arch = "wasm32")]` separate code path — `block_on` handles WASM internally

### `dash-sdk::sync` — backward compatible
- Re-exports `block_on` and `AsyncError` from `dash-async`
- All existing `use dash_sdk::sync::block_on` imports continue to work unchanged
- `retry` function and its tests remain in `dash-sdk`

### `rs-context-provider`
- Moved `From<AsyncError> for ContextProviderError` impl here (orphan rule — `AsyncError` is no longer local to `dash-sdk`)

## How Has This Been Tested?

- `cargo test -p dash-async` — 2 tests pass:
  - `test_block_on_nested_async_sync` — multi-thread runtime with nested async→sync→async calls
  - `test_block_on_fails_on_current_thread_runtime` — **regression test for #3432**: proves `block_on` works correctly on a current-thread runtime (the exact scenario that caused the deadlock)
- `cargo test -p dash-sdk --lib -- sync::test` — 40 retry tests pass
- `cargo test -p rs-sdk-trusted-context-provider` — 8 tests pass
- `cargo check` succeeds for all affected crates

## Breaking Changes

None. All public APIs are backward compatible via re-exports.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

<sub>🤖 Co-authored by [Claudius the Magnificent](https://github.com/lklimek/claudius) AI Agent</sub>

## Summary by CodeRabbit

* **New Features**
  * Added async-to-sync bridging functionality supporting multiple Tokio runtime configurations (no runtime, current-thread, multi-thread).

* **Improvements**
  * Consolidated async-to-sync logic into a shared component to reduce code duplication across packages.
  * Enhanced error handling for async operations across the workspace.

### CODE REVIEW

**Comment by thepastaclaw** [comment]
✅ Review complete (commit 5787e41f)

**Review by QuantumExplorer — APPROVED** [review]

**Review by thepastaclaw — COMMENTED** [review]
## Code Review

The assigned detached HEAD `5787e41fad1f5ee835b138171ca06c27423d6507` changes only `parse_quorum_public_key()` in `packages/rs-sdk-trusted-context-provider/src/provider.rs`, replacing lowercase-only prefix stripping with explicit `0x`/`0X` handling. That code change is correct, but there is no focused test covering the new uppercase `0X` path, so this regression fix can be lost silently in a later refactor.

*Reviewed commit: 5787e41f*

🟡 1 suggestion(s)

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `packages/rs-sdk-trusted-context-provider/src/provider.rs`:
- [SUGGESTION] lines 552-556: Add a regression test for uppercase `0X` quorum key prefixes
  This commit broadens `parse_quorum_public_key()` to accept uppercase `0X` as well as lowercase `0x`, but the module has no unit test that exercises the new branch. Because the helper is private and reached indirectly through cache and network code, a future cleanup could revert to lowercase-only handling without any test failure. Add a focused test that asserts both prefix casings decode to the same `[u8;48]` value.
```
</details>

File: packages/rs-sdk-trusted-context-provider/src/provider.rs [hunk 1]
```diff
@@ -543,6 +544,31 @@ impl TrustedHttpContextProvider {
...
+
+    /// Parse a BLS quorum public key from its hex representation.
+    ///
+    /// Accepts an optional `0x` prefix. Returns `ContextProviderError::Generic`
+    /// on invalid hex, wrong length (must be 48 bytes), or conversion failure.
+    fn parse_quorum_public_key(key: &str) -> Result<[u8; 48], ContextProviderError> {
+        let pubkey_hex = key
+            .strip_prefix("0x")
+            .or_else(|| key.strip_prefix("0X"))
+            .unwrap_or(key);
```
Comment (thepastaclaw) [inline packages/rs-sdk-trusted-context-provider/src/provider.rs:556]: **🟡 Suggestion: Add a regression test for uppercase `0X` quorum key prefixes**

This commit broadens `parse_quorum_public_key()` to accept uppercase `0X` as well as lowercase `0x`, but the module has no unit test that exercises the new branch. Because the helper is private and reached indirectly through cache and network code, a future cleanup could revert to lowercase-only handling without any test failure. Add a focused test that asserts both prefix casings decode to the same `[u8;48]` value.

<sub>source: ['codex']</sub>

<details>
<summary>🤖 Fix this with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `packages/rs-sdk-trusted-context-provider/src/provider.rs`:
- [SUGGESTION] lines 552-556: Add a regression test for uppercase `0X` quorum key prefixes
  This commit broadens `parse_quorum_public_key()` to accept uppercase `0X` as well as lowercase `0x`, but the module has no unit test that exercises the new branch. Because the helper is private and reached indirectly through cache and network code, a future cleanup could revert to lowercase-only handling without any test failure. Add a focused test that asserts both prefix casings decode to the same `[u8;48]` value.
```
</details>
